source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do
    
pod 'PINRemoteImage', '1.2'
pod 'DACircularProgress'
pod 'pop'

end
